name: model-training-action
on: [push]
jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        name: Setup Python
        with:
          python-version: "3.9"

      - run: pip install -r requirements.txt
        name: Install Requirements

      - run: pytest
        name: Run Tests

      - run: python src/train.py
        name: Train Model

      - uses: actions/upload-artifact@v2
        name: Upload Model
        with:
          name: model.pickle
          path: data/models/model.pickle
